name: dart_kaonavi_api_sample
description: A sample command-line application.
version: 1.0.0
author: ikemura kazutaka <k_ikemura@yumemi.co.jp>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.12.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
